### ISSUE TITLE
com.google.android.gms:play-services-basement version mismatch

### ISSUE THREAD

**Issue by guidolodetti** [nearit/Android-SDK#26]
Hi!

Gradle gives me strange sync errors about a `com.google.android.gms:play-services-basement` version mismatch. Googling the error I had to [add this line in the app build.gradle](https://stackoverflow.com/a/50922399/1494499) file to suppress the error. I think it is related to a Google Play Services version mismatch, but I couldn't find the cause.

This is my current app build.gradle:

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'net.danlew:android.joda:2.9.9'
    implementation 'com.plattysoft.leonids:LeonidsLib:1.3.2'
    implementation 'com.android.volley:volley:1.1.1'
    implementation 'it.near.sdk:nearit:2.10.1'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.facebook.android:facebook-android-sdk:4.38.1'
}

apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

**Comment by catt-stefano** [comment]
Hi Guido, thanks for the report.

We researched the issue and we pinpoint it to our dependency on `com.google.firebase:firebase-core:16.0.0` that includes an unfortunate dependency management by the Firebase team. They have since fixed it and now suggest to start from at least the `16.0.1` version.

We have a new library version in development with plenty of dependency updates that will prevent most of these issues, but to make sure that it will cover your scenario can you please try to include this line in your app gradle file:
`implementation 'com.google.firebase:firebase-core:16.0.1'`
and remove
`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`
and see if it syncs correctly?
If so, we'll go ahead and release the updated version (in which none of the snippets above will need to be included)

**Comment by guidolodetti** [comment]
It works! Thanks.
